---
# Copy Job xml to be used in virtual machine
- name: make tmp directory to place default job files
  sudo: yes
  shell: mkdir -p {{ remote_tmp_folder }}/jobs
  notify:
    - 'Delete Remote Temporary Folder'

- name: make tmp directory to place java pipeline job files
  sudo: yes
  shell: mkdir -p {{ remote_tmp_folder }}/jobs/java_pipeline
  notify:
    - 'Delete Remote Temporary Folder'

- name: make tmp directory to place utility database jobs for java pipeline
  sudo: yes
  shell: mkdir -p {{ remote_tmp_folder }}/jobs/java_pipeline/db_utilities
  notify:
    - 'Delete Remote Temporary Folder'

- name: make tmp directory to place mean pipeline job files
  sudo: yes
  shell: mkdir -p {{ remote_tmp_folder }}/jobs/mean_pipeline
  notify:
    - 'Delete Remote Temporary Folder'

- include: copy-files.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
