---
# Add Setup task files
# Include all sub task files here
# Tasks will be executed in the order they appear here

- include: jenkins-master-install.yml tags=presetupmaster
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- include: generate-rsa-key-pair.yml tags=presetupmaster
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ] and install_tomcat
