---
# Modify config file
- name: Set Git Name in Git Plugin Config
  sudo: yes
  shell: "groovy {{ remote_tmp_folder }}/script/updatenode.groovy -n globalConfigName -v '{{ git.name }}' {{ jenkins_home }}/{{ plugin_config_files.git_scm }}"
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ] and plugin_config_files is defined and plugin_config_files.git_scm is defined
  register: set_git_name

- name: Set Git Email in Git Plugin Config
  sudo: yes
  shell: "groovy {{ remote_tmp_folder }}/script/updatenode.groovy -n globalConfigEmail -v '{{ git.email }}' {{ jenkins_home }}/{{ plugin_config_files.git_scm }}"
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ] and set_git_name|success
  register: set_git_email
