---
# Modify config file
- name: Set rally server in Rally Plugin Config
  sudo: yes
  shell: "groovy {{ remote_tmp_folder }}/script/updatenode.groovy -n rallyServer -v '{{ rally.server }}' {{ jenkins_home }}/{{ plugin_config_files.rally_build_notifier }}"
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ] and plugin_config_files is defined and plugin_config_files.rally_build_notifier is defined
  register: set_rally_server

- name: Set username/email in Rally Plugin Config
  sudo: yes
  shell: "groovy {{ remote_tmp_folder }}/script/updatenode.groovy -n username -v '{{ rally.email }}' {{ jenkins_home }}/{{ plugin_config_files.rally_build_notifier }}"
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ] and set_rally_server|success
  register: set_rally_email

- name: Set jenkins machine name in Rally Plugin Config
  sudo: yes
  shell: "groovy {{ remote_tmp_folder }}/script/updatenode.groovy -n hudsonServer -v '{{ rally.jenkins_machine }}' {{ jenkins_home }}/{{ plugin_config_files.rally_build_notifier }}"
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ] and set_rally_server|success
  register: set_rally_jenkins_machine
