---
jenkins_dest: /opt/jenkins
jenkins_home: /var/lib/jenkins
jenkins:
  deb:
    repo: 'deb http://pkg.jenkins-ci.org/debian binary/' # Jenkins repository
    key: 'http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key' # Jenkins key
    dependencies: # Jenkins dependencies
      - 'openjdk-7-jre'
      - 'openjdk-7-jdk'
      - 'git'
      - 'curl'
  cli_dest: '{{ jenkins_dest }}/jenkins-cli.jar' # Jenkins CLI destination
  updates_dest: '{{ jenkins_dest }}/updates_jenkins.json' # Jenkins updates file
plugin_config_files:
  publish_over_ssh: jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml
  rally_build_notifier: com.rallydev.integration.build.hudson.RallyBuildNotifier.xml
  git_scm: hudson.plugins.git.GitSCM.xml
plugin_config_patterns:
  rsa_key_file: \{+\s(rsa\_key\_file)\s\}+
  tomcat_web_apps: \{+\s(tomcat\.web\_apps\_folder)\s\}+
